### ISSUE TITLE
Increase request limit

### ISSUE THREAD

**Issue by Supamiu** [xivdb/api#10]
I've created a crafting application which relies on api.xivdb to resolve its informations.

Example page: https://ffxivteamcraft.firebaseapp.com/list/MUt5HgtisYUKaSB20KdGjBhdaUX2/-KrNc_fmIWkViFLsVCux

That being said, I often get some errors from the server, making some rows of the list empty (you can see it when going on the page with no cache).

Is it planned to increase the actual api call limit? I mean, because we don't have a full recursion (see #9 ) we have to do a lot of queries in order to resolve some deep informations.

**Comment by viion** [comment]
At this time there is no plan to increase it, since this is the only API out there it has a lot of usage, you would need to use a call back or delayed approach or look into caching techniques similar to what apakkufalls uses

**Comment by Supamiu** [comment]
I have a cache system but it's client-sided because I don't have any ways to cache it on server side (the server side is a firebase database)

**Comment by viion** [comment]
You can cache in Firebase, you would populate it with data. I've done something very similar, I built a PHP script to go through and "crawl" XIVDB and grab the little bits I need, then throw this in a JSON. That can be dumped into Firebase "AsIs" under the entry `xivdb-data`, then you can pull that collection and reference it in your application locally.

This approach is one where you pull data and keep it all locally. You only need to pull data from XIVDB whenever a game patch is out as the data never changes until then :)

I know it's a bit tricky!

**Comment by Supamiu** [comment]
So he has a script on his local machine that updates his database cache? This might be a solution but I feel like it's a bit ugly because it requires me to call a local script whenever there's a patch and I want to update data, even if I only need to cache items and recipes tho (maybe enemies too later on).

That being said, do you have any idea of the volume it would require to store this? I saw that big recipes were around 6Ko each, considering ~40K recipes it's around 240Mo but I don't have any idea for item details (only the amount of items would be enough for me to compute the average size).

**Comment by viion** [comment]
I'm not sure on the size, but yes that is what he does. A lot of sites do this rather than call XIVDB directly for each query as it's faster and if XIVDB goes down, their services are not affected. Since it only has to be run every patch it's quite easy.

You can kind of make it automatic, you can cache http://api.xivdb.com/data/patchlist and whenever it changes you know XIVDB has updated and you can redownload everything, You could even just download the new stuff using the patch number against the Search API

It's a lot more work, but a challenge :)
