### ISSUE TITLE
Inconsistent leve_client ID

### ISSUE THREAD

**Issue by bmacadre** [xivdb/api#11]
If I get a Leve from API I found a `leve_client` entry but the id in this entry don't correspond to anybody....

For exemple :
`https://api.xivdb.com/leve/25`

return some data and an entry like this :
`"leve_client": {
"id": 19,
"name": "Client: Lanverlais, De La 1re Lance Des Vigiles Sombres",
"patch": 0
},`

But id 19 is useless 'cause no NPC have this id, and if I search for `lanverlais` I get an id of 1001868. NPC don't have leve entry too so I can't actually link leve with correct NPC client...

**Comment by viion** [comment]
`leve_client` is not an NPC as such, it's a clientele  (this can be more than 1 body). This is how it is in the data files, it isn't inconsistent.

Since levequests can be issued by multiple NPC's there is no direct link.

**Comment by bmacadre** [comment]
Ok, I thought that the client was the NPC who needs items (or kills, or anything else). This NPC is logicaly unique.

Is there a way to known this NPC for a particular leve ? Or do I add this info by hand ?

**Comment by viion** [comment]
Probably by hand, otherwise you would need to go datamining and map the data as this hasn't already been mapped I believe. This is a similar issue to Quests

**Comment by bmacadre** [comment]
Ok I'll see that. Thanks !
