### ISSUE TITLE
Search for character sometimes is empty even if character exists

### ISSUE THREAD

**Issue by Supamiu** [xivdb/api#13]
Following #5, I'm adding authentication to my current app and after that I'm asking the player for his character name and his server name, to fill out a `search` request.

The issue is that because characters are not pulled directly if they are not added to xivsync, I sometimes get empty results if the character is not synced and I ask for him using the search service.

Because I don't have the lodestone id (the main goal of this popup is to avoid bad UX with a lodestoneId field), I can't call xivsync right now.

Is there a possible solution for this kind of issues or should I directly use a html client to call lodestone's search engine?

**Comment by viion** [comment]
You can search on xivsync using name, e.g. https://xivsync.com/character/search?name=Eee+yoshida

Searched characters will auto add to xivdb after a few minutes, could work for you?

If you use PHP I wrote a library called lodestone-PHP which xivsync will
Move to soon

**Comment by Supamiu** [comment]
Unfortunately i'm using javascript because I have no backend (full front-end tool).

A few minutes is really a long time to wait for a user I think, it would work like "Your character is not found, please check the name or try again in a few minutes" which is fine but not the best I was hoping for ^^

Anyways it should be enough for now, if I need a faster solution I'll try to implement html-based search for lodestone, but that's not for now :smile:

**Comment by viion** [comment]
XIVSync is a tracker, if you search for a character on XIVSync you are not searching its database, it is parsing Lodestone live, so you will ALWAYS find characters on Sync. Any time a character is searched I auto-add it to XIVDB but this takes a few minutes to sync to XIVDB.

You could implement a html-based search but it will not be any faster for you, Lodestone is in Tokyo and so is XIVSync, not to mention you cannot ajax lodestone...

The URL I gave you to search is doing a real-time search against lodestone. This is also the same for any route you use against XIVSync, it's database is not accessible outside of XIVDB.

**Comment by Supamiu** [comment]
Nice ! Is it possible for you to add `classjobs` attribute to xivsync search results? It's the only reason why I'm using xivdb for characters at the moment.

**Comment by viion** [comment]
lol GitHub broken

You can use https://xivsync.com/character/parse/730968

It's not possible to add classjob as it's not part of the search data outside of an unknown icon and level
