### ISSUE TITLE
Properly handle 404 errors on /character

### ISSUE THREAD

**Issue by Supamiu** [xivdb/api#4]
(Only tested with /character)

When you call `GET /character/<lodestoneId>` with an inexistant lodestoneId, you get the generic 404 error from xivdb.com but there's not CORS headers in this page, meaning that if you call `GET /character/<lodestoneId>` from a front-end application, you have no way to handle 404 error since the preflight request will fail (no Access-Control-Allow-Origin) and it will trigger an un-catcheable error.

**Comment by viion** [comment]
This has been fixed! For all content and should work for all api requests:

- (No content) http://api.xivdb.com/item/123123123123
- (No character) http://api.xivdb.com/character/123123123123
- (No page) http://api.xivdb.com/itwefwefwef

It should also respond 404 HTTP code as well as `Access-Control-Allow-Origin:*`

**Comment by Supamiu** [comment]
Tested, it works.

So fast, thank you :+1:
