### ISSUE TITLE
Character not found even if it exists ingame

### ISSUE THREAD

**Issue by Supamiu** [xivdb/api#5]
When I call `GET https://api.xivdb.com/character/8062661`, 

I have a 404 error, but the character actually exists:

http://na.finalfantasyxiv.com/lodestone/character/8062661

This character has been created 2 years ago so it's a strange issue, I don't really know what to add about that.

I also looked for this charatcer on xivdb.com and got no results.

**Comment by viion** [comment]
XIVDB doesn't pull directly from Lodestone. If it isn't on XIVDB then you won't get an API response.

I don't currently obtain all characters, there are automated ways but the scale is too large to manage right now.

To get the character on XIVDB and tracking it has to be added to the site :)

**Comment by Supamiu** [comment]
How can one add his character to XIVDB?

**Comment by viion** [comment]
You can call this url to get them on the sync tracking service: https://xivsync.com/character/add/8062661

After a few minutes it shows up on XIVDB :)

**Comment by Supamiu** [comment]
got it, thank you ! :+1:
