### ISSUE TITLE
Recipe depth limited?

### ISSUE THREAD

**Issue by Supamiu** [xivdb/api#9]
Taking as example this resource : https://api.xivdb.com/recipe/32431

Here is a basic recipe tree we can create from the recipe ingame:

```
Wind-up Susano
    1x Worsted Yarn
        ...
    2x Dawn Serge
        3x Worsted Yarn
              ...
    1x Kyanite
        ...
```

Problem is that the first `Worsted Yarn` (in the recipe root has a synths attribute because it's a pre-requisite craft made by `WVR` but the second time we see it (in the tree of `Dawn Serge`) it has no synths attribute, meaning that if we want to base a parser on this, it's impossible because if it has no synths, it's supposed to be a non-craftable item but it is.

Is this a bug or is it by design? If it's by design, how to know for sure if an item is craftable in a recipe tree?

**Comment by Supamiu** [comment]
Alright, it means that if I want to know more about an item in the tree, I have to check if it has a connect_recipe property > 0 and if it has one, I have to get the details of the recipe with a new http request?

**Comment by viion** [comment]
Well internally you can save the recipe for the top layer one and then further down you can record it, otherwise yeah you would need to a second request to get further details.

**Comment by Supamiu** [comment]
My goal is to avoid server-side cache because I'm using firebase so I need to get all the informations of a recipe using api.xivdb. The only things I store are the ids of the recipes and of the items so the database can serve that and the client just has to `GET /item/[id]` or `/recipe/[id]`.
